backend:
  name: 'github'
  repo: 'WolvenKit/wolvenkit-www'

media_folder: 'static/img'
public_folder: '/img'

i18n:
  structure: 'multiple_folders'
  locales: [en, cn, es, fr, jp, tr]
  default_locale: 'en'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    i18n: true
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        i18n: true
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'D MMMM YYYY'
      - label: 'Description'
        name: 'description'
        widget: 'string'
        i18n: true
      - label: 'Thumbnail Image'
        name: 'thumbnailImage'
        widget: 'image'
        allow_multiple: false
        i18n: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        i18n: true

  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    i18n: true
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: 'name'
    editor:
      preview: false
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
        i18n: true
      - label: 'GitHub Link'
        name: 'link'
        widget: 'string'
        required: false
      - label: 'Get Started Link'
        name: 'getStarted'
        widget: 'string'
        required: false
      - label: 'Download Link'
        name: 'download'
        widget: 'string'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        allow_multiple: false
        required: false
      - label: 'Color'
        name: 'color'
        widget: 'color'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        i18n: true

  - name: 'team'
    label: 'Team'
    folder: 'content/team'
    format: 'yaml'
    create: true
    slug: '{{slug}}'
    identifier_field: 'name'
    editor:
      preview: false
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'Profile Image'
        name: 'profileImage'
        widget: 'image'
        allow_multiple: false
        required: false
      - label: 'Projects'
        name: 'projects'
        widget: 'relation'
        collection: 'projects'
        value_field: 'name'
        search_fields: ['name']
        multiple: true
        required: false
      - label: 'Country (alpha-2)'
        name: 'country'
        widget: 'string'
        required: false
      - label: 'Socials'
        label_singular: 'Social'
        name: 'socials'
        widget: 'list'
        required: false
        summary: '{{fields.service}} - {{fields.link}}'
        fields:
          - label: 'Service'
            name: 'service'
            widget: 'select'
            options: ['github', 'twitter', 'reddit', 'web']
          - label: 'Link'
            name: 'link'
            widget: 'string'
